apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZWR1YXJkb2FtZW5kb2xhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJU5oNHZaOXBYQnFAZlVVZm0qQ1kiLCJhdXRoIjoiWldSMVlYSmtiMkZ0Wlc1a2IyeGhRR2R0WVdsc0xtTnZiVG9sVG1nMGRsbzVjRmhDY1VCbVZWVm1iU3BEV1E9PSJ9fX0=
kind: Secret
metadata:
  name: python-demo-secret
type: kubernetes.io/dockerconfigjson
